#!/usr/bin/env bash

set -euo pipefail

CACHE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QWEN35_SOURCE_DIR="$(cd "$CACHE_SCRIPT_DIR/../.." && pwd)"
REPO_ROOT="$(cd "$QWEN35_SOURCE_DIR/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env}"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

die() {
  echo "error: $*" >&2
  exit 2
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

require_cache_s3_uri() {
  [[ -n "${QWEN35_COMPILER_CACHE_S3_URI:-}" ]] ||
    die "set QWEN35_COMPILER_CACHE_S3_URI in $ENV_FILE or the environment"
  CACHE_S3_URI="${QWEN35_COMPILER_CACHE_S3_URI%/}"
  [[ "$CACHE_S3_URI" =~ ^s3://[^/]+(/.*)?$ ]] ||
    die "QWEN35_COMPILER_CACHE_S3_URI must be an s3:// URI"
  CACHE_S3_ARGS=()
  if [[ -n "${QWEN35_COMPILER_CACHE_S3_REGION:-}" ]]; then
    CACHE_S3_ARGS+=(--region "$QWEN35_COMPILER_CACHE_S3_REGION")
  fi
}

validate_cache_key() {
  local key="$1"
  [[ "$key" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] ||
    die "cache key must contain only letters, digits, dot, underscore, and hyphen"
}

resolve_cache_dir() {
  local supplied="${1:-}"
  local cache_dir="${supplied:-${QWEN35_COMPILER_CACHE_DIR:-}}"
  [[ -n "$cache_dir" ]] ||
    die "pass a cache directory or set QWEN35_COMPILER_CACHE_DIR in $ENV_FILE"
  printf '%s\n' "${cache_dir%/}"
}

cache_prefix() {
  printf '%s/%s\n' "$CACHE_S3_URI" "$1"
}

cache_payload_uri() {
  printf '%s/cache/\n' "$(cache_prefix "$1")"
}

cache_manifest_uri() {
  printf '%s/manifest.env\n' "$(cache_prefix "$1")"
}

assert_cache_root() {
  local cache_dir="$1"
  [[ -d "$cache_dir" ]] || die "cache directory does not exist: $cache_dir"
  [[ -d "$cache_dir/neff_cache" ]] ||
    die "cache directory has no neff_cache subtree: $cache_dir"
  [[ -n "$(find "$cache_dir/neff_cache" -type f -name '*.neff' -print -quit)" ]] ||
    die "cache directory has no NEFF files: $cache_dir"
}

cache_file_count() {
  find "$1" -type f | wc -l | tr -d '[:space:]'
}

cache_neff_count() {
  find "$1" -type f -name '*.neff' | wc -l | tr -d '[:space:]'
}

cache_byte_count() {
  du -sb "$1" | awk '{print $1}'
}

cache_neff_tree_sha256() {
  (
    cd "$1"
    find neff_cache -type f -name '*.neff' -print0 |
      sort -z |
      xargs -0 sha256sum |
      sha256sum |
      awk '{print $1}'
  )
}

directory_is_nonempty() {
  [[ -d "$1" && -n "$(find "$1" -mindepth 1 -maxdepth 1 -print -quit)" ]]
}

assert_safe_replace_target() {
  local cache_dir="$1"
  [[ "$cache_dir" != "/" && "$cache_dir" != "." && "$cache_dir" != ".." ]] ||
    die "refusing to replace unsafe cache directory: $cache_dir"
}

write_manifest() {
  local manifest="$1"
  local key="$2"
  local cache_dir="$3"
  local compile_metadata="$cache_dir/qwen35_compile_metadata.env"
  local revision="unknown"
  local detected_revision

  if [[ -f "$compile_metadata" ]]; then
    # Generated by deploy/compile_prefill_trn2.sh from fixed, shell-quoted keys.
    # shellcheck disable=SC1090
    source "$compile_metadata"
  fi

  if detected_revision="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null)"; then
    revision="$detected_revision"
  fi

  cat >"$manifest" <<EOF
schema_version=2
cache_key=$key
created_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)
cache_root_basename=$(basename "$cache_dir")
cache_files=$(cache_file_count "$cache_dir")
neff_files=$(cache_neff_count "$cache_dir")
cache_bytes=$(cache_byte_count "$cache_dir")
neff_tree_sha256=$(cache_neff_tree_sha256 "$cache_dir")
git_revision=$revision
native_image=${QWEN35_NATIVE_IMAGE:-unknown}
native_image_resolved=${QWEN35_NATIVE_IMAGE_RESOLVED:-unknown}
neuronx_cc_version=${QWEN35_NEURONX_CC_VERSION:-unknown}
host_nrt_library=${QWEN35_HOST_NRT_LIBRARY:-unknown}
host_nrt_sha256=${QWEN35_HOST_NRT_SHA256:-unknown}
platform_target_shim_sha256=${QWEN35_PLATFORM_TARGET_SHIM_SHA256:-unknown}
cache_platform_target=${QWEN35_CACHE_PLATFORM_TARGET:-unknown}
physical_platform_target=${QWEN35_PHYSICAL_PLATFORM_TARGET:-unknown}
source_archive_sha256=${QWEN35_SOURCE_ARCHIVE_SHA256:-unknown}
source_status_sha256=${QWEN35_SOURCE_STATUS_SHA256:-unknown}
nkilib_revision=${QWEN35_NKILIB_REVISION:-unknown}
nkilib_status_sha256=${QWEN35_NKILIB_STATUS_SHA256:-unknown}
nkilib_archive_sha256=${QWEN35_NKILIB_ARCHIVE_SHA256:-unknown}
compile_host=${QWEN35_COMPILE_HOST:-unknown}
compile_region=${QWEN35_COMPILE_REGION:-unknown}
topology_tp=${QWEN35_TP:-unknown}
topology_lnc=${QWEN35_LNC:-unknown}
batch_size=${QWEN35_BATCH_SIZE:-unknown}
num_layers=${QWEN35_NUM_LAYERS:-unknown}
max_seq_len=${QWEN35_MAX_SEQ_LEN:-unknown}
prefill_tokens=${QWEN35_PREFILL_TOKENS:-unknown}
bucket_chunk=${QWEN35_BUCKET_CHUNK:-unknown}
prefill_splits=${QWEN35_PREFILL_SPLITS:-unknown}
chunk_size=${CHUNK_SIZE:-unknown}
moe_cte_block=${MOE_CTE_BLOCK:-unknown}
neuron_cc_flags=${NEURON_CC_FLAGS:-unknown}
platform_target_override_scope=${QWEN35_CACHE_PLATFORM_TARGET_SCOPE:-unknown}
compile_command_sha256=${QWEN35_COMPILE_COMMAND_SHA256:-unknown}
cache_layout=complete_container_tmp_mount
required_container_mount=/tmp
EOF
}

manifest_value() {
  local manifest="$1"
  local key="$2"
  awk -F= -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "$manifest"
}

assert_manifest_match() {
  local manifest="$1"
  local manifest_key="$2"
  local expected="$3"
  local actual

  [[ -n "$expected" ]] || return 0
  actual="$(manifest_value "$manifest" "$manifest_key")"
  [[ -n "$actual" && "$actual" != "unknown" ]] ||
    die "cache manifest has no $manifest_key for compatibility validation"
  [[ "$actual" == "$expected" ]] ||
    die "cache $manifest_key mismatch: manifest=$actual requested=$expected"
}

assert_manifest_compatible() {
  local manifest="$1"

  assert_manifest_match "$manifest" native_image_resolved "${QWEN35_NATIVE_IMAGE_RESOLVED:-}"
  assert_manifest_match "$manifest" source_archive_sha256 "${QWEN35_SOURCE_ARCHIVE_SHA256:-}"
  assert_manifest_match "$manifest" nkilib_revision "${QWEN35_NKILIB_REVISION:-}"
  assert_manifest_match "$manifest" nkilib_archive_sha256 "${QWEN35_NKILIB_ARCHIVE_SHA256:-}"
  assert_manifest_match "$manifest" platform_target_shim_sha256 "${QWEN35_PLATFORM_TARGET_SHIM_SHA256:-}"
  assert_manifest_match "$manifest" cache_platform_target "${QWEN35_CACHE_PLATFORM_TARGET:-}"
  assert_manifest_match "$manifest" topology_tp "${QWEN35_TP:-}"
  assert_manifest_match "$manifest" topology_lnc "${QWEN35_LNC:-}"
  assert_manifest_match "$manifest" batch_size "${QWEN35_BATCH_SIZE:-}"
  assert_manifest_match "$manifest" num_layers "${QWEN35_NUM_LAYERS:-}"
  assert_manifest_match "$manifest" max_seq_len "${QWEN35_MAX_SEQ_LEN:-}"
  assert_manifest_match "$manifest" prefill_tokens "${QWEN35_PREFILL_TOKENS:-}"
  assert_manifest_match "$manifest" bucket_chunk "${QWEN35_BUCKET_CHUNK:-}"
  assert_manifest_match "$manifest" prefill_splits "${QWEN35_PREFILL_SPLITS:-}"
  assert_manifest_match "$manifest" neuron_cc_flags "${NEURON_CC_FLAGS:-}"
}
